#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# 1) Mesh in parallel with prism layers = false.
# 2) Turn off castellated and snap, and turn on prism layers in snappyHexMesh.
# 3) Run this script in loop.

rm -r ./log* ./postProcessing ./processor*/1
rm -r ./0
cp -r 0.Base 0

runParallel snappyHexMesh
runApplication reconstructParMesh

cp -r ./1/polyMesh ./constant
rm -r ./1


# Create the inlet/outlet, AMI patches and reconstructMesh
runApplication createBaffles -overwrite
runApplication mergeOrSplitBaffles -split -overwrite
runApplication renumberMesh -noFields -overwrite

runApplication mapFields -mapMethod mapNearest ../compressor -sourceTime 'latestTime' -consistent
rm ./0/yPlus ./0/u ./0/rho ./0/wallShearStress ./0/Ur ./0/Ut
runApplication $(getApplication) -postProcess -func yPlus


#------------------------------------------------------------------------------
