#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -r ./log* ./postProcessing ./processor* ./0/u ./0/rho ./0/Ur ./0/Ut ./0/yPlus ./0/wallShearStress

runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar -latestTime

mv log.turboSimpleFoam log.turboSimpleFoamMain

runApplication $(getApplication) -postProcess -func yPlus
mv log.turboSimpleFoam log.turboSimpleFoamYPlus

runApplication $(getApplication) -postProcess -func wallShearStress
mv log.turboSimpleFoam log.turboSimpleFoamWallShearStress


#------------------------------------------------------------------------------
